### ISSUE TITLE
Update ecephys align timestamps to allow barcode_ephys line label variant

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#12]
The get_barcode_line of the align_timestamps module searches for barcode in several variations of sync file line labels that have been encountered.  There is a new variation used by Visual Behavior Neuropixels: ephys_barcode

As defined in the excel file linked in the "Sync: PCIe 6612 DAQ" section of [this confluence page](http://confluence.corp.alleninstitute.org/display/ENG/Neuropixels+Pipeline+Line+Labels).

Need to enable processing using this new line label.  (Add another `elif`?)

Probably worth checking if there are other places in the code where the new line labels break old implementations.

**Comment by njmei** [comment]
More details:

Simple fix would be to add new `elif` clause to:

https://github.com/AllenInstitute/AllenSDK/blob/b29058f4c136f906123b3f93cd184edb9158b4e4/allensdk/brain_observatory/ecephys/align_timestamps/barcode_sync_dataset.py#L13

We may want to consider this an opportunity to move the whole `align_timestamps` module over to the `ecephys_etl_pipelines` repo though:

https://github.com/AllenInstitute/AllenSDK/tree/master/allensdk/brain_observatory/ecephys/align_timestamps

Estimate of 1-2 if just putting in the fast fix.
Estimate of 3-5 if moving the whole module over from AllenSDK + putting in fast fix
