### ISSUE TITLE
Create NWB2 files for Visual Behavior Neuropixels

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#14]
In order for the Visual Behavior Neuropixels project to start analyzing and QC'ing their data, the experiments need to be in NWB2 format.  This also is required in order to release the data near the end of 2021 or sometime in 2022.

This epic tracks the work items required to generate valid and complete NWB2 files for data from this project.

**Comment by danielsf** [comment]
Closing this, as it is redundant with #21
