### ISSUE TITLE
Move extract_frame_times_from_photodiode functions to ecephys repo

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#15]
Move the VCN extract_frame_times_from_photodiode() implementation and dependencies into ecephys_etl_pipelines repository.

Tasks:
- [ ] Understand the  extract_frame_times_from_photodiode() function and all dependencies in the AllenSDK ecephys code base
- [ ] Move it to ecephys_etl_pipelines (git subtree function to retain commit history)
- [ ] Move over existing tests
- [ ] Determine if there are glaring deficiencies in test coverage and correct

Validation criteria:
- [ ] PR merged

**Comment by njmei** [comment]
Turns out this move was already done in: https://github.com/AllenInstitute/ecephys_etl_pipelines/pull/3

Closing this ticket as it's not needed.
