### ISSUE TITLE
Run sessions through pipeline

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#27]
After the monitor delay #20 and running speed #9 issues are merged, then run all Visual Behavior Neuropixels sessions through pipeline starting with VBN_CREATE_STIM_TABLE_QUEUE.  Investigate failures.  If successfully run through pipeline, then provide output files to Corbett for inspection.

Note that these are likely to fail in the ECEPHYS_WRITE_NWB_QUEUE which is expected (still need to design the module to write NWB files for this project).

**Comment by ns706** [comment]
I've run everything through the monitor delay queue (VBN_CREATE_STIM_TABLE_QUEUE) and I have shown the results to Corbett to look at.

**Comment by ns706** [comment]
19 jobs have failed in the ECEPHYS_ALIGN_TIMESTAMPS_QUEUE due missing probes.

'Error: No probes with all required data.'

**Comment by wbwakeman** [comment]
I did some LIMS pipeline tweaks.
* Removed job_transition from align-timestamps to filtered_running speed since all VBN sessions will get current_source_density
* update job_transition from current source density so that transition to filtered_running_speed had a higher priority.  In order to make use of other criteria in the transition (such as project), then the transition needs a higher priority than the default
* update the jobs that had incorrectly transitionted to ecephys_extract_running_speed and failed there.  These are now queued up in the filtered_running_speed queue waiting for the production deployment of that strategy.
* While we are waiting for that, maybe we could run some through the optotagging queue?  Not sure if that relies on the output from a successful running_speed job or not.

**Comment by wbwakeman** [comment]
Corbett  provided an updated "complete" list of VBN experiments.  Need to ensure that all of these have run through the pipeline
https://alleninstitute-my.sharepoint.com/:x:/g/personal/waynew_alleninstitute_org/EW0GoBznyJJJvpFPrlPN_MwBbaaCz9_Z03aXCF6hyUKK_Q?e=GyLWnI
