### ISSUE TITLE
Get acquainted with AllenSDK Data Object organization

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#28]
To begin addressing issue #9 to design the session object for Visual Behavior Neuropixels data, Nathan needs to get acquainted with the data structures that we are using now to organize and make available data for Visual Behavior sessions.  

Tasks:
Get familiar with Data Object organization of AllenSDK for Visual Behavior two-photon
Ask Adam and Nick for more information about how this is organized and start to get ideas for how to apply this organization to Visual Behavior Neuropixels sessions
Start to document ideas for organizing VBN sessions

**Comment by wbwakeman** [comment]
@ns706 Where have you started to document ideas for organizing VBN sessions?

**Comment by ns706** [comment]
I've met with Adam for a detailed run through of this. I've created a documentation page here:

https://alleninstitute-brainscience.atlassian.net/wiki/spaces/ITP/pages/1003683841/AllenSDK+Data+Object+organization+for+VBN
