### ISSUE TITLE
Update data release tool with new VBN project plugin

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#31]
Update data release tool with new visual behavior Neuropixels project plugin

https://github.com/AllenInstitute/informatics_data_release_tools/blob/main/src/data_release_tools/project_specific_plugins/adding_new_plugins.rst

The input to the data release tool needs to be a project level metadata (*.csv) writer. 

One will need to be written for visual behavior neuropixels. This is the one for visual behavior ophys (but double check with Adam Amster):

https://github.com/AllenInstitute/AllenSDK/blob/master/allensdk/brain_observatory/behavior/behavior_project_cache/external/behavior_project_metadata_writer.py

project name: visual-behavior-neuropixels
project release date: 2022-04-28

In addition to above, there are some tasks for Wayne:
- [ ] Update LIMS records for release sessions and well_known_files to match this release date.
- [ ] Create and provide a query with relevant metadata for these sessions and probes (part of #32)

Tasks
- [ ] Write the plug-in described above for Neuropixels
- [ ] Implement whatever S3 infrastructure is required in a sandbox (should be readily translatable to the BTV space when we are ready for the actual release)

Validation
- [ ] Data can be uploaded to an S3 sandbox

**Comment by danielsf** [comment]
Here is a cartoon example of what we need to implement

https://github.com/AllenInstitute/informatics_data_release_tools/blob/danielsf/cartoon/release/src/data_release_tools/project_specific_plugins/cartoon_plugin.py

**Comment by danielsf** [comment]
Whoever takes on this ticket will probably need to converse with whoever takes on ticket #33, mostly to make sure that the `file_id` and `local_file_path` column generated by the metadata writer are what this plugin expects.
