### ISSUE TITLE
Upload CCF files for VBN release

### ISSUE THREAD

**Issue by danielsf** [AllenInstitute/ecephys_etl_pipelines#36]
**When Corbett delivers the full set of CCF data files**, we need to upload them to LIMS using the datafix script provided by Wayne (link forthcoming). It is possible we can ask Zeb Harandon to run the query for us

Once Corbett provides the CCF annotation files:

- Make sure to uncomment `create_ldds_row` command (that is how LIMS avoids running the same datafix twice)
- Datafix ruby script should point at that folder and iterate through it.
- Change `  parent_dir = "/allen/programs/braintv/workgroups/neuralcoding/corbettb/VBN_production"` to point to wherever Corbett is putting his data files.
- Datafix script needs to be put into the `datafixes/` folder; there is a script in LIMS that runs through every datafix and runs it automatically.
- To test it locally use something akin to `rails r db/datafixes/your_datafix_name`

Tasks
- [x] Upload CCF data to LIMS using the script Wayne links to below
- [x] Edit datafix script as described above
- [x] Merge into `datafixes/` folder in LIMS
- [x] Request new release of LIMS (which will cause the datafix script to be run)

Validation
- [x] SQL query provided by Wayne shows that the CCF data was successfully uploaded

**Comment by wbwakeman** [comment]
A LIMS db query to check ecephys_channels that will be updated by the datafix script:
```
SELECT es.id AS es_id, ep.id AS ep_id, ep.name AS ep, ec.*
FROM ecephys_sessions es 
JOIN ecephys_probes ep ON ep.ecephys_session_id=es.id
JOIN ecephys_channels ec ON ec.ecephys_probe_id=ep.id
WHERE 
--es.published_at IS NOT NULL
es.id = 1055403683 AND ep.name = 'probeF' 
ORDER BY es.id,ep.name,ec.local_index;
```

Datafix script is /allen/aibs/technology/waynew/ecephys_ccf_coord/202203110909_pbs1874_datafix.rb and in [this gist](https://gist.github.com/wbwakeman/c832140412edb746c769906e2d8d762a)
