### ISSUE TITLE
Design Session Object for Visual Behavior Neuropixels

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/ecephys_etl_pipelines#9]
In preparation for creating Visual Behavior Neuropixel NWB files, and creating methods to access the data in them, need to design the session object for this data.  This should use new DataObject interface architecture.
This does not need a "from_lims" database method; can use json snapshot only.

Tasks:
[ ] Design interface to pull data from LIMS to populate container
[ ] Document the specific fields required for this data
[ ] Document the source of data for each of these fields (and how it gets to the object)

Validation criteria:
[ ] Confluence page listing specific details for each field to be populated, including source of the data

**Comment by ns706** [comment]
I will be putting the documentation for this issue on this page: https://alleninstitute-brainscience.atlassian.net/wiki/spaces/ITP/pages/1003683841/AllenSDK+Data+Object+organization+for+VBN
